In [33]:
import pandas as pd
import numpy as np
import math

In [34]:
df = pd.read_csv('datasets/dataset_train.csv', index_col = 0 )

In [35]:
df = df[df.columns[5:]]
columns = df.columns
df.describe()

,Arithmancy,Astronomy,Herbology,Defense Against the Dark Arts,Divination,Muggle Studies,Ancient Runes,History of Magic,Transfiguration,Potions,Care of Magical Creatures,Charms,Flying
count,1566.000000,1568.000000,1567.000000,1569.000000,1561.000000,1565.000000,1565.000000,1557.000000,1566.000000,1570.000000,1560.000000,1600.000000,1600.000000
mean,49634.570243,39.797131,1.141020,-0.387863,3.153910,-224.589915,495.747970,2.963095,1030.096946,5.950373,-0.053427,-243.374409,21.958012
std,16679.806036,520.298268,5.219682,5.212794,4.155301,486.344840,106.285165,4.425775,44.125116,3.147854,0.971457,8.783640,97.631602
min,-24370.000000,-966.740546,-10.295663,-10.162119,-8.727000,-1086.496835,283.869609,-8.858993,906.627320,-4.697484,-3.313676,-261.048920,-181.470000
25%,38511.500000,-489.551387,-4.308182,-5.259095,3.099000,-577.580096,397.511047,2.218653,1026.209993,3.646785,-0.671606,-250.652600,-41.870000
50%,49013.500000,260.289446,3.469012,-2.589342,4.624000,-419.164294,463.918305,4.378176,1045.506996,5.874837,-0.044811,-244.867765,-2.515000
75%,60811.250000,524.771949,5.419183,4.904680,5.667000,254.994857,597.492230,5.825242,1058.436410,8.248173,0.589919,-232.552305,50.560000
max,104956.000000,1016.211940,11.612895,9.667405,10.032000,1092.388611,745.396220,11.889713,1098.958201,13.536762,3.056546,-225.428140,279.070000

In [36]:
def ft_del_nun(column):
    array = [i for i in column if i == i]
    return array

def ft_count(column):
    return(len(column))

def ft_mean(count, column):
    sum = 0
    for i in column:
        sum += i
    return(round(sum / count, 6))

def ft_std(mean, column, count):
    result = 0
    for i in column:
        result += (i - mean) ** 2
    result =  math.sqrt(result / (count - 1))
    return(round(result, 6))

def ft_min(column):
    result = column[0]
    for i in column:
        if i < result:
            result = i
    return(result)

def ft_max(column):
    result = column[0]
    for i in column:
        if i > result:
            result = i
    return(result)

def ft_per(column, count, p):
    column = sorted(column)
    count = (count - 1) * p
    floor = int(np.floor(count))
    ceil = int(np.ceil(count))
    if floor == ceil:
        return(column[int(count)]) 
    else:
        delta = (column[ceil] - column[floor]) * (count - floor) + column[floor]
        return delta

In [37]:
table = pd.DataFrame()
table['describe'] = ['count', 'mean', 'std', 'min', '25%', '50%', '75%', 'max']
table = table.set_index('describe')

for name_column in columns:
    values_column = ft_del_nun(df[name_column])
    count = ft_count(values_column)
    mean = ft_mean(count, values_column)
    std = ft_std(mean, values_column, count) 
    min_value = ft_min(values_column)
    max_value = ft_max(values_column)
    per_50 = ft_per(values_column, count, 0.5)
    per_25 = ft_per(values_column, count, 0.25)
    per_75 = ft_per(values_column, count, 0.75)
    res = [count, mean, std, min_value, per_25, per_50, per_75, max_value]
    table[name_column] = res

38511.5 -489.551387 -4.308182 -5.259095 3.099 -577.580096 397.511047 2.218653 1026.209993 3.646785 -0.671606 -250.6526 -41.87

In [38]:
table

,Arithmancy,Astronomy,Herbology,Defense Against the Dark Arts,Divination,Muggle Studies,Ancient Runes,History of Magic,Transfiguration,Potions,Care of Magical Creatures,Charms,Flying
describe,,,,,,,,,,,,,
count,1566.000000,1568.000000,1567.000000,1569.000000,1561.000000,1565.000000,1565.000000,1557.000000,1566.000000,1570.000000,1560.000000,1600.000000,1600.000000
mean,49634.570243,39.797131,1.141020,-0.387863,3.153910,-224.589915,495.747970,2.963095,1030.096946,5.950373,-0.053427,-243.374409,21.958012
std,16679.806036,520.298268,5.219682,5.212794,4.155301,486.344840,106.285165,4.425775,44.125116,3.147854,0.971457,8.783640,97.631602
min,-24370.000000,-966.740546,-10.295663,-10.162119,-8.727000,-1086.496835,283.869609,-8.858993,906.627320,-4.697484,-3.313676,-261.048920,-181.470000
25%,38511.500000,-489.551387,-4.308182,-5.259095,3.099000,-577.580096,397.511047,2.218653,1026.209993,3.646785,-0.671606,-250.652600,-41.870000
50%,49013.500000,260.289446,3.469012,-2.589342,4.624000,-419.164294,463.918305,4.378176,1045.506996,5.874837,-0.044811,-244.867765,-2.515000
75%,60811.250000,524.771949,5.419183,4.904680,5.667000,254.994857,597.492230,5.825242,1058.436410,8.248173,0.589919,-232.552305,50.560000
max,104956.000000,1016.211940,11.612895,9.667405,10.032000,1092.388611,745.396220,11.889713,1098.958201,13.536762,3.056546,-225.428140,279.070000